# Generated by Django 5.0.6 on 2024-07-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alumno_avatar_alumno_edad_alumno_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='avatar',
        ),
    ]
