# Generated by Django 5.0.6 on 2024-07-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
